name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v5.0.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_username: AlphaMycelium
        pypi_password: ${{ secrets.PYPI_PASSWORD }}
